services:
  - type: web
    name: portfolio-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: static
    name: portfolio-frontend
    staticPublishPath: ./client/dist
    buildCommand: cd client && npm install && npm run build
    routes:
      - path: /
        destination: /index.html
